services:
  - type: web
    name: discord-todo-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python start_bot.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: DATA_DIR
        value: /opt/render/project/src/data
    disk:
      name: todo-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1 